// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLZw6WN3O3GTb5l2ERAX6OJLokmH7t7mE',
    appId: '1:264766558325:web:32501646b9f32dc0f8683c',
    messagingSenderId: '264766558325',
    projectId: 'dizisalon-e373b',
    authDomain: 'dizisalon-e373b.firebaseapp.com',
    storageBucket: 'dizisalon-e373b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO6qet5CJ5OORc3ashBzNcZODYoigzX4U',
    appId: '1:264766558325:android:b495494e7aed8221f8683c',
    messagingSenderId: '264766558325',
    projectId: 'dizisalon-e373b',
    storageBucket: 'dizisalon-e373b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAixUSj2pdKw7aTlmJ57R-5u8nyWltRsL4',
    appId: '1:264766558325:ios:ab7207e3216e0268f8683c',
    messagingSenderId: '264766558325',
    projectId: 'dizisalon-e373b',
    storageBucket: 'dizisalon-e373b.firebasestorage.app',
    iosBundleId: 'com.example.dizisalonVender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAixUSj2pdKw7aTlmJ57R-5u8nyWltRsL4',
    appId: '1:264766558325:ios:ab7207e3216e0268f8683c',
    messagingSenderId: '264766558325',
    projectId: 'dizisalon-e373b',
    storageBucket: 'dizisalon-e373b.firebasestorage.app',
    iosBundleId: 'com.example.dizisalonVender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLZw6WN3O3GTb5l2ERAX6OJLokmH7t7mE',
    appId: '1:264766558325:web:cf85fa10a4f296fff8683c',
    messagingSenderId: '264766558325',
    projectId: 'dizisalon-e373b',
    authDomain: 'dizisalon-e373b.firebaseapp.com',
    storageBucket: 'dizisalon-e373b.firebasestorage.app',
  );

}